name: Check for unwanted words

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-for-words:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Search for unwanted words in code
      run: |
        if grep -R ${{ secrets.UNWANTED_WORD }} ./*; then
          echo "Found ${{ secrets.UNWANTED_WORD }} in code"
          exit 1
        else
          echo "${{ secrets.UNWANTED_WORD }} not found in code"
        fi
    - name: Search for unwanted words in commit messages
      run: |
        if git log -S ${{ secrets.UNWANTED_WORD }} | grep -q ${{ secrets.UNWANTED_WORD }}; then
          echo "Found ${{ secrets.UNWANTED_WORD }} in commit messages"
          exit 1
        else
          echo "${{ secrets.UNWANTED_WORD }} not found in commit messages"
        fi

